import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { 
  Milestone, 
  CheckSquare, 
  Square, 
  Map, 
  ArrowRight,
  Zap,
  CheckCircle,
  HelpCircle
} from 'lucide-react';
import { Link } from 'react-router-dom';

const RoadmapGenerator = () => {
  const [roadmap, setRoadmap] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    fetchActiveRoadmap();
  }, []);

  const fetchActiveRoadmap = async () => {
    try {
      const data = await api.roadmaps.getCurrent();
      setRoadmap(data);
    } catch (err) {
      console.warn('No active roadmap found:', err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleTopicToggle = async (weekIdx, topicIdx) => {
    if (!roadmap) return;
    setSaving(true);

    const plan = JSON.parse(roadmap.generatedPlan);
    
    // Toggle topic completion state (we represent completed as index trackers or mutate the plan structure)
    // To make it simple: let's toggle completed state inside topics array if stored as objects, 
    // or toggle standard completed checkmark on week modules.
    // Let's toggle completed status of the week if all topics checked, or simple click week module.
    // Let's support week toggle or simple topic list toggle:
    const weekModule = plan[weekIdx];
    if (!weekModule.completedTopics) {
        weekModule.completedTopics = [];
    }
    
    const topic = weekModule.topics[topicIdx];
    const isCompleted = weekModule.completedTopics.includes(topic);
    
    if (isCompleted) {
        weekModule.completedTopics = weekModule.completedTopics.filter(t => t !== topic);
    } else {
        weekModule.completedTopics.push(topic);
    }

    // Update module's completed state if all topics are checked
    weekModule.completed = weekModule.completedTopics.length === weekModule.topics.length;

    // Recalculate total percentage completed
    let totalTopicsCount = 0;
    let completedTopicsCount = 0;
    plan.forEach(w => {
        totalTopicsCount += w.topics.length;
        completedTopicsCount += (w.completedTopics ? w.completedTopics.length : (w.completed ? w.topics.length : 0));
    });

    const completionPercentage = Math.round((completedTopicsCount * 100) / totalTopicsCount);

    try {
      const updatedPlanJson = JSON.stringify(plan);
      const updated = await api.roadmaps.updateProgress(updatedPlanJson, completionPercentage);
      setRoadmap(updated);
    } catch (err) {
      console.error(err);
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[500px]">
        <div className="w-10 h-10 border-4 border-brand-blue border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  // Parse current plan JSON
  const plan = roadmap ? JSON.parse(roadmap.generatedPlan) : [];

  return (
    <div className="space-y-8 animate-fade-in">
      <div>
        <h1 className="text-3xl font-black tracking-tight">AI Roadmap</h1>
        <p className="text-gray-400 mt-1">Implement weekly curriculums generated by skill audits.</p>
      </div>

      {!roadmap ? (
        <div className="p-12 bg-white dark:bg-dark-card border border-gray-200 dark:border-dark-border rounded-3xl text-center max-w-xl mx-auto flex flex-col items-center justify-center">
          <div className="w-14 h-14 bg-gray-50 dark:bg-dark-bg border border-gray-200 dark:border-dark-border rounded-2xl flex items-center justify-center mb-6">
            <Map className="text-brand-purple" size={28} />
          </div>
          <h3 className="font-bold text-lg">No Active Roadmap</h3>
          <p className="text-xs text-gray-400 mt-2 mb-6 max-w-sm">
            Roadmaps are automatically generated based on missing skill audits. Head to the Skill Gap tab first.
          </p>
          <Link
            to="/skill-gap"
            className="px-6 py-3 bg-gradient-to-r from-brand-blue to-brand-purple text-white font-semibold rounded-xl hover:opacity-90 shadow-md flex items-center space-x-2 text-xs"
          >
            <span>Run Skill Audit</span>
            <ArrowRight size={14} />
          </Link>
        </div>
      ) : (
        <div className="space-y-6">
          {/* Progress Banner Header */}
          <div className="p-6 bg-white dark:bg-dark-card border border-gray-200 dark:border-dark-border rounded-3xl">
            <div className="flex items-center justify-between text-sm mb-3">
              <div>
                <span className="font-semibold text-gray-400 uppercase tracking-widest text-xs">Active Track</span>
                <h3 className="font-black text-lg mt-0.5">{roadmap.targetRole} Roadmap</h3>
              </div>
              <span className="text-2xl font-black text-brand-purple">{roadmap.completionPercentage}%</span>
            </div>
            
            <div className="w-full bg-gray-100 dark:bg-dark-bg h-3.5 rounded-full overflow-hidden relative">
              <div 
                className="bg-gradient-to-r from-brand-blue to-brand-purple h-full rounded-full transition-all duration-500"
                style={{ width: `${roadmap.completionPercentage}%` }}
              ></div>
            </div>
            
            {saving && (
              <p className="text-[10px] text-brand-purple font-semibold animate-pulse mt-2 text-right">Saving progress...</p>
            )}
          </div>

          {/* Timeline Layout */}
          <div className="relative pl-8 border-l border-gray-200 dark:border-dark-border space-y-8 py-4 ml-4">
            {plan.map((weekData, weekIdx) => (
              <div key={weekIdx} className="relative">
                {/* Timeline node */}
                <div className={`absolute -left-12.5 top-0 w-8 h-8 rounded-full border-2 flex items-center justify-center z-10 transition duration-150 bg-white dark:bg-dark-card ${weekData.completed 
                  ? 'border-emerald-500 text-emerald-500' 
                  : 'border-gray-300 text-gray-400'}`}
                >
                  {weekData.completed ? <CheckCircle size={16} className="fill-emerald-50" /> : <span className="text-xs font-bold">{weekData.week}</span>}
                </div>

                {/* Week card content */}
                <div className="p-6 bg-white dark:bg-dark-card border border-gray-200 dark:border-dark-border rounded-3xl space-y-4">
                  <div>
                    <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Week {weekData.week}</span>
                    <h4 className="font-bold text-md mt-0.5">{weekData.title}</h4>
                  </div>

                  {/* Checklist of topics */}
                  <div className="space-y-2">
                    {weekData.topics.map((topic, topicIdx) => {
                      const isTopicCompleted = weekData.completedTopics && weekData.completedTopics.includes(topic);
                      return (
                        <button
                          key={topicIdx}
                          onClick={() => handleTopicToggle(weekIdx, topicIdx)}
                          className="w-full flex items-center text-left space-x-3 p-2.5 hover:bg-gray-50 dark:hover:bg-dark-bg/60 rounded-xl transition group text-sm"
                        >
                          {isTopicCompleted ? (
                            <CheckSquare className="text-brand-purple group-hover:opacity-80 shrink-0" size={18} />
                          ) : (
                            <Square className="text-gray-300 dark:text-gray-500 group-hover:text-brand-purple shrink-0" size={18} />
                          )}
                          <span className={isTopicCompleted ? 'line-through text-gray-400 dark:text-gray-500' : 'font-medium text-gray-600 dark:text-gray-300'}>
                            {topic}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default RoadmapGenerator;
